// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAioFX5vme5vhga3WqwK_5uFECGPktGAQU',
    appId: '1:944486425338:web:74a8f7b51029798dcd1f43',
    messagingSenderId: '944486425338',
    projectId: 'coppa-d9156',
    authDomain: 'coppa-d9156.firebaseapp.com',
    storageBucket: 'coppa-d9156.appspot.com',
    measurementId: 'G-7FSKB3J3DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABUfEozR2ZFzCsgrSi3u5YomS-Fko_x80',
    appId: '1:944486425338:android:93a59d74297b6d24cd1f43',
    messagingSenderId: '944486425338',
    projectId: 'coppa-d9156',
    storageBucket: 'coppa-d9156.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlslBUfacB5J8k7fuNGg2_XVKvjSJn_44',
    appId: '1:944486425338:ios:51a7a1ed9d9e5bf9cd1f43',
    messagingSenderId: '944486425338',
    projectId: 'coppa-d9156',
    storageBucket: 'coppa-d9156.appspot.com',
    iosClientId: '944486425338-dlbsirgkfpmv9uot6ooi4jkq633cgnq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGetxLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlslBUfacB5J8k7fuNGg2_XVKvjSJn_44',
    appId: '1:944486425338:ios:51a7a1ed9d9e5bf9cd1f43',
    messagingSenderId: '944486425338',
    projectId: 'coppa-d9156',
    storageBucket: 'coppa-d9156.appspot.com',
    iosClientId: '944486425338-dlbsirgkfpmv9uot6ooi4jkq633cgnq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGetxLearn',
  );
}
